package r4

import (
	"compress/gzip"
	"encoding/json"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
	"sync"
)

// ─────────────────────────────────────────────────────────────────────────────
// valueSetFile mirrors the JSON written by cmd/build-terminology/build_terminology.py
// ─────────────────────────────────────────────────────────────────────────────

type valueSetFile struct {
	URL             string   `json:"url"`
	Name            string   `json:"name"`
	Codes           []string `json:"codes"`
	CaseInsensitive bool     `json:"caseInsensitive"`
	ExternalSystems []string `json:"externalSystems"` // e.g. ["SNOMED CT","LOINC"]
	FetchFailed     bool     `json:"fetchFailed"`
}

// compiledValueSet is the in-memory form after loading.
type compiledValueSet struct {
	codes           map[string]struct{} // already lowercased if CaseInsensitive
	caseInsensitive bool
	externalSystems []string // non-empty → disclosure needed
	fetchFailed     bool     // true → no codes, unknown content
}

// ─────────────────────────────────────────────────────────────────────────────
// TerminologyRegistry
// ─────────────────────────────────────────────────────────────────────────────

// TerminologyRegistry implements TerminologyLookup.
// It is populated from pre-compiled .gz files generated by build_terminology.py,
// covering all 568 ValueSets referenced across R4 resource + US Core schemas.
// Zero network calls are made at runtime.
type TerminologyRegistry struct {
	mu   sync.RWMutex
	sets map[string]*compiledValueSet // normalizedURL → compiled set
}

var (
	globalTermRegistry     *TerminologyRegistry
	globalTermRegistryOnce sync.Once
)

func init() {
	globalTermRegistry = &TerminologyRegistry{
		sets: make(map[string]*compiledValueSet),
	}
}

// GetTerminologyRegistry returns the package-level singleton.
func GetTerminologyRegistry() *TerminologyRegistry {
	return globalTermRegistry
}

// InitTerminology loads all ValueSet .gz files from valuesetDir.
// Called from InitRegistry so the same schemaDir root is reused:
//
//	schemaDir/R4/valuesets/*.gz
func InitTerminology(valuesetDir string) error {
	entries, err := os.ReadDir(valuesetDir)
	if err != nil {
		return fmt.Errorf("terminology: cannot read %s: %w", valuesetDir, err)
	}

	loaded := 0
	skipped := 0

	globalTermRegistry.mu.Lock()
	defer globalTermRegistry.mu.Unlock()

	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".gz") {
			continue
		}
		path := filepath.Join(valuesetDir, e.Name())
		f, err := os.Open(path)
		if err != nil {
			skipped++
			continue
		}
		gr, err := gzip.NewReader(f)
		if err != nil {
			f.Close()
			skipped++
			continue
		}
		var vsf valueSetFile
		if err := json.NewDecoder(gr).Decode(&vsf); err != nil {
			gr.Close()
			f.Close()
			skipped++
			continue
		}
		gr.Close()
		f.Close()

		url := normalizeValueSetURL(vsf.URL)
		compiled := &compiledValueSet{
			codes:           make(map[string]struct{}, len(vsf.Codes)),
			caseInsensitive: vsf.CaseInsensitive,
			externalSystems: vsf.ExternalSystems,
			fetchFailed:     vsf.FetchFailed,
		}
		for _, code := range vsf.Codes {
			key := code
			if vsf.CaseInsensitive {
				key = strings.ToLower(key)
			}
			compiled.codes[key] = struct{}{}
		}
		globalTermRegistry.sets[url] = compiled
		loaded++
	}

	log.Printf("[r4/terminology] Loaded %d ValueSets (%d skipped) from %s",
		loaded, skipped, valuesetDir)
	return nil
}

// ─────────────────────────────────────────────────────────────────────────────
// Public lookup API
// ─────────────────────────────────────────────────────────────────────────────

// Contains implements TerminologyLookup (unchanged interface).
//
//	inSet=true  → code is a recognised member of the ValueSet.
//	known=false → the ValueSet was not in our compiled files; treat as pass-through.
func (tr *TerminologyRegistry) Contains(valueSetURL, code string) (inSet, known bool) {
	inSet, known, _ = tr.ContainsEx(valueSetURL, code)
	return
}

// TerminologyResult is the extended result returned by ContainsEx.
type TerminologyResult struct {
	InSet           bool
	Known           bool     // false → ValueSet not found in compiled files
	ExternalSystems []string // non-empty → disclosure message should be emitted
	FetchFailed     bool     // true → tx.fhir.org could not expand this VS at build time
}

// ContainsEx returns the full result including external-system disclosure info.
// Used by the validator to attach information-level issues when licensed codes
// are involved.
func (tr *TerminologyRegistry) ContainsEx(valueSetURL, code string) (inSet, known bool, external []string) {
	url := normalizeValueSetURL(valueSetURL)

	tr.mu.RLock()
	vs, ok := tr.sets[url]
	tr.mu.RUnlock()

	if !ok {
		// Not in compiled files → fall through to legacy hardcoded check
		inSet, known = tr.legacyContains(url, code)
		return inSet, known, nil
	}

	known = true

	if vs.fetchFailed {
		// Build-time expansion failed → we have no codes, can't validate
		return false, true, nil
	}

	lookupCode := code
	if vs.caseInsensitive {
		lookupCode = strings.ToLower(code)
	}
	_, found := vs.codes[lookupCode]

	if found {
		return true, true, vs.externalSystems
	}

	// Code not in embedded set.
	// If this VS also includes external systems (SNOMED/LOINC/etc.), the code
	// might be valid there — return external list so validator can disclose.
	if len(vs.externalSystems) > 0 {
		return false, true, vs.externalSystems
	}

	return false, true, nil
}

// ─────────────────────────────────────────────────────────────────────────────
// Legacy hardcoded fallback (retained for ValueSets not in the .gz files)
// ─────────────────────────────────────────────────────────────────────────────

// legacyContains checks the small set of hardcoded codes that were present
// before the file-based registry was introduced.  It is only reached when a
// ValueSet URL is absent from the compiled .gz files.
func (tr *TerminologyRegistry) legacyContains(url, code string) (inSet, known bool) {
	codes, ok := legacyCodes[url]
	if !ok {
		return false, false
	}
	c := strings.ToLower(code)
	return codes[c] || codes[code], true
}

// legacyCodes is the original hardcoded table — kept as a last-resort fallback.
// Now that we load from files, this is only reached for ValueSets that were
// somehow absent from the build-time download.
var legacyCodes = map[string]map[string]bool{
	"http://hl7.org/fhir/ValueSet/observation-status": {
		"registered": true, "preliminary": true, "final": true,
		"amended": true, "corrected": true, "cancelled": true,
		"entered-in-error": true, "unknown": true,
	},
	"http://hl7.org/fhir/ValueSet/administrative-gender": {
		"male": true, "female": true, "other": true, "unknown": true,
	},
	"http://hl7.org/fhir/ValueSet/encounter-status": {
		"planned": true, "arrived": true, "triaged": true, "in-progress": true,
		"onleave": true, "finished": true, "cancelled": true,
		"entered-in-error": true, "unknown": true,
	},
	"http://hl7.org/fhir/ValueSet/condition-clinical": {
		"active": true, "recurrence": true, "relapse": true,
		"inactive": true, "remission": true, "resolved": true,
	},
	"http://hl7.org/fhir/ValueSet/condition-ver-status": {
		"unconfirmed": true, "provisional": true, "differential": true,
		"confirmed": true, "refuted": true, "entered-in-error": true,
	},
	"http://hl7.org/fhir/ValueSet/bundle-type": {
		"document": true, "message": true, "transaction": true,
		"transaction-response": true, "batch": true, "batch-response": true,
		"history": true, "searchset": true, "collection": true,
	},
	"http://hl7.org/fhir/ValueSet/http-verb": {
		"get": true, "head": true, "post": true, "put": true,
		"delete": true, "patch": true,
	},
	"http://hl7.org/fhir/ValueSet/name-use": {
		"usual": true, "official": true, "temp": true, "nickname": true,
		"anonymous": true, "old": true, "maiden": true,
	},
	"http://hl7.org/fhir/ValueSet/address-use": {
		"home": true, "work": true, "temp": true, "old": true, "billing": true,
	},
	"http://hl7.org/fhir/ValueSet/address-type": {
		"postal": true, "physical": true, "both": true,
	},
	"http://hl7.org/fhir/ValueSet/contact-point-system": {
		"phone": true, "fax": true, "email": true, "pager": true,
		"url": true, "sms": true, "other": true,
	},
	"http://hl7.org/fhir/ValueSet/contact-point-use": {
		"home": true, "work": true, "temp": true, "old": true, "mobile": true,
	},
	"http://hl7.org/fhir/ValueSet/identifier-use": {
		"usual": true, "official": true, "temp": true, "secondary": true, "old": true,
	},
	"http://hl7.org/fhir/ValueSet/diagnostic-report-status": {
		"registered": true, "partial": true, "preliminary": true, "final": true,
		"amended": true, "corrected": true, "appended": true, "cancelled": true,
		"entered-in-error": true, "unknown": true,
	},
	"http://hl7.org/fhir/ValueSet/immunization-status": {
		"completed": true, "entered-in-error": true, "not-done": true,
	},
	"http://hl7.org/fhir/ValueSet/medicationrequest-status": {
		"active": true, "on-hold": true, "cancelled": true, "completed": true,
		"entered-in-error": true, "stopped": true, "draft": true, "unknown": true,
	},
	"http://hl7.org/fhir/ValueSet/medicationrequest-intent": {
		"proposal": true, "plan": true, "order": true, "original-order": true,
		"reflex-order": true, "filler-order": true, "instance-order": true,
		"option": true,
	},
	"http://hl7.org/fhir/ValueSet/allergy-intolerance-category": {
		"food": true, "medication": true, "environment": true, "biologic": true,
	},
}
