// controllers/schema_fhir_transform_controller.go
// Enhanced version with UI support - complete implementation
package controllers

import (
	"database/sql"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"

	"ezhealthkonnect/config"
	"ezhealthkonnect/fhir/r4"

	"github.com/gin-gonic/gin"
)

// listAvailableSchemaNames formats every profile in reg as "{version}_{profile}_{resourceType}"
// (e.g. "R4_base_Patient", "R4_us-core_Patient") — the same shape the legacy
// fhir.FHIRSchemaLoader.ListAvailableSchemas() used, since this is a
// diagnostics endpoint whose response shape external callers may already
// depend on.
func listAvailableSchemaNames(reg *r4.SchemaRegistry) []string {
	var names []string
	for _, version := range []string{"R4", "R5"} {
		for _, key := range reg.List(version) {
			names = append(names, fmt.Sprintf("%s_%s_%s", key.Version, key.Profile, key.ResourceType))
		}
	}
	return names
}

// =====================================
// ENHANCED SCHEMA-DRIVEN FHIR CONTROLLER
// =====================================

type SchemaFHIRTransformController struct {
	db     *sql.DB
	config *config.Config
}

// =====================================
// DATA STRUCTURES FOR UI
// =====================================

type MappingRule struct {
	ID             int                    `json:"id"`
	HL7MessageType string                 `json:"hl7MessageType"`
	HL7Segment     string                 `json:"hl7Segment"`
	HL7Field       string                 `json:"hl7Field"`
	HL7Component   *string                `json:"hl7Component,omitempty"`
	FHIRResource   string                 `json:"fhirResource"`
	FHIRProfile    string                 `json:"fhirProfile"`
	FHIRPath       string                 `json:"fhirPath"`
	TransformLogic map[string]interface{} `json:"transformLogic"`
	ConditionExpr  *string                `json:"conditionExpr,omitempty"`
	Confidence     string                 `json:"confidence"` // high, medium, low
	Priority       int                    `json:"priority"`
	Required       bool                   `json:"required"`
	Enabled        bool                   `json:"enabled"`
	AutoGenerated  bool                   `json:"autoGenerated"`
	CreatedAt      time.Time              `json:"createdAt"`
	UpdatedAt      time.Time              `json:"updatedAt"`
}

type HL7FieldStructure struct {
	Segment     string               `json:"segment"`
	Fields      []HL7FieldDefinition `json:"fields"`
	Description string               `json:"description"`
}

type HL7FieldDefinition struct {
	Field       string                   `json:"field"`
	Name        string                   `json:"name"`
	Description string                   `json:"description"`
	DataType    string                   `json:"dataType"`
	Required    bool                     `json:"required"`
	Repeatable  bool                     `json:"repeatable"`
	Components  []HL7ComponentDefinition `json:"components,omitempty"`
}

type HL7ComponentDefinition struct {
	Component string `json:"component"`
	Name      string `json:"name"`
	DataType  string `json:"dataType"`
	Required  bool   `json:"required"`
}

type FHIRResourceStructure struct {
	ResourceType string                `json:"resourceType"`
	Profile      string                `json:"profile"`
	Fields       []FHIRFieldDefinition `json:"fields"`
	Required     []string              `json:"required"`
	MustSupport  []string              `json:"mustSupport"`
}

type FHIRFieldDefinition struct {
	Path        string  `json:"path"`
	Name        string  `json:"name"`
	Type        string  `json:"type"`
	Description string  `json:"description"`
	Required    bool    `json:"required"`
	MustSupport bool    `json:"mustSupport"`
	Cardinality string  `json:"cardinality"`
	ValueSet    *string `json:"valueSet,omitempty"`
}

// =====================================
// CONTROLLER INITIALIZATION
// =====================================

// NewSchemaFHIRTransformController used to also build a fhir.TransformationEngine
// here (fhir/transformation_engine.go) — deleted 2026-08-16 as confirmed dead
// code: the two handlers that would have called it (Transform, ValidateOnly)
// were always stubs returning 501, so the engine was constructed on every
// startup and never actually invoked.
func NewSchemaFHIRTransformController(database *sql.DB, cfg *config.Config) *SchemaFHIRTransformController {
	return &SchemaFHIRTransformController{
		db:     database,
		config: cfg,
	}
}

// =====================================
// ROUTE REGISTRATION
// =====================================

func (c *SchemaFHIRTransformController) RegisterRoutes(router *gin.RouterGroup) {
	fhirGroup := router.Group("/transform")
	{
		// Status endpoints
		fhirGroup.GET("/status", c.GetStatus)
		fhirGroup.GET("/schemas", c.ListSchemas)

		// Core transformation endpoints
		fhirGroup.POST("", c.Transform)
		fhirGroup.POST("/validate", c.ValidateOnly)

		// Rule management endpoints for UI
		fhirGroup.GET("/rules", c.GetRules)
		fhirGroup.POST("/rules", c.CreateRule)
		fhirGroup.POST("/rules/batch", c.BatchUpdateRules)
		fhirGroup.PUT("/rules/:id", c.UpdateRule)
		fhirGroup.DELETE("/rules/:id", c.DeleteRule)

		// UI-specific endpoints
		fhirGroup.GET("/config", c.GetUIConfiguration)
		fhirGroup.POST("/suggestions", c.GetMappingSuggestions)
		fhirGroup.POST("/preview", c.PreviewTransformation)
		fhirGroup.POST("/validate-mapping", c.ValidateMapping)

		// Structure endpoints for UI
		fhirGroup.GET("/structure/hl7/:messageType", c.GetHL7Structure)
		fhirGroup.GET("/structure/fhir/:profile", c.GetFHIRStructure)

		// Analytics and logging endpoints
		fhirGroup.GET("/analytics", c.GetAnalytics)
		fhirGroup.GET("/logs", c.GetTransformationLogs)
		fhirGroup.PUT("/config", c.UpdateConfiguration)
	}
}

// =====================================
// STATUS AND CONFIGURATION ENDPOINTS
// =====================================

func (c *SchemaFHIRTransformController) GetStatus(ctx *gin.Context) {
	status := map[string]interface{}{
		"status":     "operational",
		"message":    "Schema-driven FHIR transformation service",
		"version":    "1.0.0",
		"timestamp":  time.Now().Format(time.RFC3339),
		"database":   c.db != nil,
		"configured": true,
	}

	reg := r4.GetRegistry()
	if reg != nil {
		available := listAvailableSchemaNames(reg)
		status["fhirSchemas"] = map[string]interface{}{
			"available": available,
			"count":     len(available),
		}
	} else {
		status["fhirSchemas"] = map[string]interface{}{
			"available": []string{},
			"count":     0,
			"status":    "not_initialized",
		}
	}

	ctx.JSON(http.StatusOK, status)
}

func (c *SchemaFHIRTransformController) ListSchemas(ctx *gin.Context) {
	reg := r4.GetRegistry()
	if reg == nil {
		ctx.JSON(http.StatusServiceUnavailable, gin.H{
			"error": "FHIR schema registry not initialized",
		})
		return
	}

	available := listAvailableSchemaNames(reg)

	ctx.JSON(http.StatusOK, gin.H{
		"success": true,
		"schemas": available,
		"count":   len(available),
	})
}

// =====================================
// TRANSFORMATION ENDPOINTS
// =====================================

func (c *SchemaFHIRTransformController) Transform(ctx *gin.Context) {
	ctx.JSON(http.StatusNotImplemented, gin.H{
		"success": false,
		"error":   "Transform method implementation in progress",
		"message": "This endpoint will provide HL7 to FHIR transformation using existing engine",
	})
}

func (c *SchemaFHIRTransformController) ValidateOnly(ctx *gin.Context) {
	ctx.JSON(http.StatusNotImplemented, gin.H{
		"success": false,
		"error":   "ValidateOnly method implementation in progress",
		"message": "This endpoint will provide FHIR resource validation",
	})
}

// =====================================
// RULE MANAGEMENT ENDPOINTS
// =====================================

func (c *SchemaFHIRTransformController) GetRules(ctx *gin.Context) {
	messageType := ctx.Query("messageType")
	profile := ctx.DefaultQuery("profile", "base")
	includeMetadata := ctx.DefaultQuery("includeMetadata", "false") == "true"

	if messageType == "" {
		ctx.JSON(http.StatusBadRequest, gin.H{
			"success": false,
			"error":   "messageType parameter is required",
			"example": "?messageType=ADT^A01&profile=base&includeMetadata=true",
		})
		return
	}

	// Load existing rules from database
	rules, err := c.loadMappingRulesFromDB(messageType, profile)
	if err != nil {
		ctx.JSON(http.StatusInternalServerError, gin.H{
			"success": false,
			"error":   "Failed to load mapping rules",
			"details": err.Error(),
		})
		return
	}

	response := gin.H{
		"success":     true,
		"messageType": messageType,
		"profile":     profile,
		"rules":       rules,
		"count":       len(rules),
	}

	if includeMetadata {
		// Add UI-specific metadata
		hl7Structure, _ := c.getHL7StructureForMessageType(messageType)
		fhirStructure, _ := c.getFHIRStructureForProfile(profile)

		response["sourceStructure"] = hl7Structure
		response["targetStructure"] = fhirStructure
		response["mappingStats"] = c.getMappingStatistics(rules)
		response["validationIssues"] = c.validateMappingCompleteness(rules, hl7Structure, fhirStructure)
	}

	ctx.JSON(http.StatusOK, response)
}

func (c *SchemaFHIRTransformController) CreateRule(ctx *gin.Context) {
	ctx.JSON(http.StatusNotImplemented, gin.H{
		"success": false,
		"error":   "CreateRule method implementation in progress",
	})
}

func (c *SchemaFHIRTransformController) UpdateRule(ctx *gin.Context) {
	ctx.JSON(http.StatusNotImplemented, gin.H{
		"error": "UpdateRule method not yet implemented",
	})
}

func (c *SchemaFHIRTransformController) DeleteRule(ctx *gin.Context) {
	ctx.JSON(http.StatusNotImplemented, gin.H{
		"error": "DeleteRule method not yet implemented",
	})
}

func (c *SchemaFHIRTransformController) BatchUpdateRules(ctx *gin.Context) {
	var request struct {
		MessageType string        `json:"messageType" binding:"required"`
		Profile     string        `json:"profile"`
		Rules       []MappingRule `json:"rules" binding:"required"`
		AutoFix     bool          `json:"autoFix"`
	}

	if err := ctx.ShouldBindJSON(&request); err != nil {
		ctx.JSON(http.StatusBadRequest, gin.H{
			"success": false,
			"error":   "Invalid request format",
			"details": err.Error(),
		})
		return
	}

	if request.Profile == "" {
		request.Profile = "base"
	}

	// Validate rules against schemas
	validationResults := c.validateRulesAgainstSchemas(request.Rules, request.MessageType, request.Profile)

	if request.AutoFix {
		// Auto-fix common issues
		request.Rules = c.autoFixMappingIssues(request.Rules, validationResults)
		validationResults = c.validateRulesAgainstSchemas(request.Rules, request.MessageType, request.Profile)
	}

	// Save to database
	savedCount, err := c.saveRulesToDB(request.MessageType, request.Profile, request.Rules)
	if err != nil {
		ctx.JSON(http.StatusInternalServerError, gin.H{
			"success": false,
			"error":   "Failed to save mapping rules",
			"details": err.Error(),
		})
		return
	}

	ctx.JSON(http.StatusOK, gin.H{
		"success":           true,
		"saved":             savedCount,
		"validationResults": validationResults,
		"autoFixed":         request.AutoFix,
		"timestamp":         time.Now().Format(time.RFC3339),
	})
}

// =====================================
// UI-SPECIFIC ENDPOINTS
// =====================================

func (c *SchemaFHIRTransformController) GetUIConfiguration(ctx *gin.Context) {
	messageType := ctx.Query("messageType")
	profile := ctx.DefaultQuery("profile", "base")

	config := gin.H{
		"supportedMessageTypes": []string{"ADT^A01", "ORU^R01", "ORM^O01", "DFT^P03"},
		"supportedProfiles":     []string{"base", "us-core", "international"},
		"confidenceLevels":      []string{"high", "medium", "low"},
		"transformationTypes":   []string{"direct", "lookup", "calculated", "conditional"},
	}

	if messageType != "" {
		// Get specific configuration for this message type
		hl7Structure, _ := c.getHL7StructureForMessageType(messageType)
		fhirStructure, _ := c.getFHIRStructureForProfile(profile)

		config["hl7Structure"] = hl7Structure
		config["fhirStructure"] = fhirStructure
		config["defaultMappings"] = c.getDefaultMappingsForMessageType(messageType, profile)
	}

	ctx.JSON(http.StatusOK, gin.H{
		"success": true,
		"config":  config,
	})
}

func (c *SchemaFHIRTransformController) GetMappingSuggestions(ctx *gin.Context) {
	var request struct {
		MessageType string `json:"messageType" binding:"required"`
		HL7Field    string `json:"hl7Field" binding:"required"`
		Profile     string `json:"profile"`
	}

	if err := ctx.ShouldBindJSON(&request); err != nil {
		ctx.JSON(http.StatusBadRequest, gin.H{
			"success": false,
			"error":   "Invalid request format",
			"details": err.Error(),
		})
		return
	}

	if request.Profile == "" {
		request.Profile = "base"
	}

	suggestions := c.generateFieldMappingSuggestions(request.MessageType, request.HL7Field, request.Profile)

	ctx.JSON(http.StatusOK, gin.H{
		"success":     true,
		"suggestions": suggestions,
		"field":       request.HL7Field,
		"profile":     request.Profile,
	})
}

func (c *SchemaFHIRTransformController) PreviewTransformation(ctx *gin.Context) {
	ctx.JSON(http.StatusNotImplemented, gin.H{
		"success": false,
		"error":   "PreviewTransformation method implementation in progress",
	})
}

func (c *SchemaFHIRTransformController) ValidateMapping(ctx *gin.Context) {
	ctx.JSON(http.StatusNotImplemented, gin.H{
		"success": false,
		"error":   "ValidateMapping method implementation in progress",
	})
}

// =====================================
// STRUCTURE ENDPOINTS
// =====================================

func (c *SchemaFHIRTransformController) GetHL7Structure(ctx *gin.Context) {
	messageType := ctx.Param("messageType")

	if messageType == "" {
		ctx.JSON(http.StatusBadRequest, gin.H{
			"success": false,
			"error":   "messageType parameter is required",
		})
		return
	}

	structure, err := c.getHL7StructureForMessageType(messageType)
	if err != nil {
		ctx.JSON(http.StatusNotFound, gin.H{
			"success":     false,
			"error":       "HL7 structure not found",
			"messageType": messageType,
			"details":     err.Error(),
		})
		return
	}

	ctx.JSON(http.StatusOK, gin.H{
		"success":      true,
		"messageType":  messageType,
		"structure":    structure,
		"segmentCount": len(structure),
	})
}

func (c *SchemaFHIRTransformController) GetFHIRStructure(ctx *gin.Context) {
	profile := ctx.Param("profile")
	resourceType := ctx.Query("resourceType")

	if profile == "" {
		profile = "base"
	}

	structure, err := c.getFHIRStructureForProfile(profile)
	if err != nil {
		ctx.JSON(http.StatusNotFound, gin.H{
			"success": false,
			"error":   "FHIR structure not found",
			"profile": profile,
			"details": err.Error(),
		})
		return
	}

	// Filter by resource type if specified
	if resourceType != "" {
		if resource, exists := structure[resourceType]; exists {
			structure = map[string]FHIRResourceStructure{resourceType: resource}
		} else {
			ctx.JSON(http.StatusNotFound, gin.H{
				"success":      false,
				"error":        "Resource type not found in profile",
				"profile":      profile,
				"resourceType": resourceType,
			})
			return
		}
	}

	ctx.JSON(http.StatusOK, gin.H{
		"success":       true,
		"profile":       profile,
		"structure":     structure,
		"resourceCount": len(structure),
	})
}

// =====================================
// ANALYTICS AND LOGGING ENDPOINTS
// =====================================

func (c *SchemaFHIRTransformController) GetAnalytics(ctx *gin.Context) {
	ctx.JSON(http.StatusOK, gin.H{
		"success": true,
		"message": "Analytics endpoint (to be implemented)",
		"data": gin.H{
			"totalTransformations": 0,
			"successRate":          "100%",
		},
	})
}

func (c *SchemaFHIRTransformController) GetTransformationLogs(ctx *gin.Context) {
	ctx.JSON(http.StatusOK, gin.H{
		"success": true,
		"logs":    []interface{}{},
		"message": "Transformation logs endpoint (to be implemented)",
	})
}

func (c *SchemaFHIRTransformController) UpdateConfiguration(ctx *gin.Context) {
	ctx.JSON(http.StatusNotImplemented, gin.H{
		"error": "UpdateConfiguration method not yet implemented",
	})
}

// =====================================
// DATABASE OPERATIONS
// =====================================

func (c *SchemaFHIRTransformController) loadMappingRulesFromDB(messageType, profile string) ([]MappingRule, error) {
	query := `
		SELECT id, hl7_message_type, hl7_segment, hl7_field, hl7_component,
		       fhir_resource, fhir_profile, fhir_path, transformation_logic,
		       condition_expression, confidence_level, priority, is_required, 
		       is_enabled, auto_generated, created_at, updated_at
		FROM hl7_fhir_mappings 
		WHERE hl7_message_type = $1 AND fhir_profile = $2 AND is_enabled = true
		ORDER BY priority ASC, hl7_segment ASC, hl7_field ASC
	`

	rows, err := c.db.Query(query, messageType, profile)
	if err != nil {
		return nil, fmt.Errorf("failed to query mapping rules: %w", err)
	}
	defer rows.Close()

	var rules []MappingRule
	for rows.Next() {
		var rule MappingRule
		var hl7Component sql.NullString
		var conditionExpr sql.NullString
		var transformLogicJSON []byte

		err := rows.Scan(
			&rule.ID, &rule.HL7MessageType, &rule.HL7Segment, &rule.HL7Field, &hl7Component,
			&rule.FHIRResource, &rule.FHIRProfile, &rule.FHIRPath, &transformLogicJSON,
			&conditionExpr, &rule.Confidence, &rule.Priority, &rule.Required,
			&rule.Enabled, &rule.AutoGenerated, &rule.CreatedAt, &rule.UpdatedAt,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to scan mapping rule: %w", err)
		}

		// Handle nullable fields
		if hl7Component.Valid {
			rule.HL7Component = &hl7Component.String
		}
		if conditionExpr.Valid {
			rule.ConditionExpr = &conditionExpr.String
		}

		// Parse transformation logic JSON
		if len(transformLogicJSON) > 0 {
			if err := json.Unmarshal(transformLogicJSON, &rule.TransformLogic); err != nil {
				return nil, fmt.Errorf("failed to parse transformation logic for rule %d: %w", rule.ID, err)
			}
		} else {
			rule.TransformLogic = map[string]interface{}{"type": "direct"}
		}

		rules = append(rules, rule)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("error iterating mapping rules: %w", err)
	}

	return rules, nil
}

func (c *SchemaFHIRTransformController) saveRulesToDB(messageType, profile string, rules []MappingRule) (int, error) {
	tx, err := c.db.Begin()
	if err != nil {
		return 0, fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer tx.Rollback()

	// Delete existing rules for this message type and profile
	deleteQuery := `
		DELETE FROM hl7_fhir_mappings 
		WHERE hl7_message_type = $1 AND fhir_profile = $2
	`
	_, err = tx.Exec(deleteQuery, messageType, profile)
	if err != nil {
		return 0, fmt.Errorf("failed to delete existing rules: %w", err)
	}

	// Insert new rules
	insertQuery := `
		INSERT INTO hl7_fhir_mappings (
			hl7_message_type, hl7_segment, hl7_field, hl7_component,
			fhir_resource, fhir_profile, fhir_path, transformation_logic,
			condition_expression, confidence_level, priority, is_required,
			is_enabled, auto_generated, created_by
		) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
	`

	savedCount := 0
	for _, rule := range rules {
		transformLogicJSON, err := json.Marshal(rule.TransformLogic)
		if err != nil {
			return savedCount, fmt.Errorf("failed to marshal transformation logic: %w", err)
		}

		_, err = tx.Exec(insertQuery,
			rule.HL7MessageType, rule.HL7Segment, rule.HL7Field, rule.HL7Component,
			rule.FHIRResource, rule.FHIRProfile, rule.FHIRPath, transformLogicJSON,
			rule.ConditionExpr, rule.Confidence, rule.Priority, rule.Required,
			rule.Enabled, rule.AutoGenerated, "ui-system",
		)
		if err != nil {
			return savedCount, fmt.Errorf("failed to insert rule: %w", err)
		}
		savedCount++
	}

	if err := tx.Commit(); err != nil {
		return savedCount, fmt.Errorf("failed to commit transaction: %w", err)
	}

	return savedCount, nil
}

// =====================================
// HELPER METHODS
// =====================================

func (c *SchemaFHIRTransformController) getHL7StructureForMessageType(messageType string) (map[string]HL7FieldStructure, error) {
	// TODO: Integrate with your existing HL7 schema system (hl7/parser.go, real_schema_parser.go)
	// For now, return basic ADT^A01 structure
	if messageType == "ADT^A01" {
		return map[string]HL7FieldStructure{
			"MSH": {
				Segment:     "MSH",
				Description: "Message Header",
				Fields: []HL7FieldDefinition{
					{Field: "MSH.3", Name: "Sending Application", DataType: "HD", Required: true},
					{Field: "MSH.7", Name: "Date/Time of Message", DataType: "TS", Required: true},
					{Field: "MSH.10", Name: "Message Control ID", DataType: "ST", Required: true},
				},
			},
			"PID": {
				Segment:     "PID",
				Description: "Patient Identification",
				Fields: []HL7FieldDefinition{
					{Field: "PID.3", Name: "Patient Identifier List", DataType: "CX", Required: true},
					{Field: "PID.5", Name: "Patient Name", DataType: "XPN", Required: true},
					{Field: "PID.7", Name: "Date/Time of Birth", DataType: "TS", Required: false},
					{Field: "PID.8", Name: "Administrative Sex", DataType: "IS", Required: false},
					{Field: "PID.11", Name: "Patient Address", DataType: "XAD", Required: false},
					{Field: "PID.13", Name: "Phone Number - Home", DataType: "XTN", Required: false},
				},
			},
		}, nil
	}
	return map[string]HL7FieldStructure{}, fmt.Errorf("message type %s not supported", messageType)
}

func (c *SchemaFHIRTransformController) getFHIRStructureForProfile(profile string) (map[string]FHIRResourceStructure, error) {
	// TODO: Integrate with your existing FHIR schema system (fhir/schema_loader.go)
	// For now, return basic structure
	return map[string]FHIRResourceStructure{
		"Patient": {
			ResourceType: "Patient",
			Profile:      profile,
			Fields: []FHIRFieldDefinition{
				{Path: "Patient.identifier", Name: "Identifier", Type: "Identifier", Required: true, MustSupport: true},
				{Path: "Patient.name", Name: "Name", Type: "HumanName", Required: true, MustSupport: true},
				{Path: "Patient.birthDate", Name: "Birth Date", Type: "date", Required: false, MustSupport: true},
				{Path: "Patient.gender", Name: "Gender", Type: "code", Required: false, MustSupport: true},
				{Path: "Patient.address", Name: "Address", Type: "Address", Required: false, MustSupport: false},
				{Path: "Patient.telecom", Name: "Telecom", Type: "ContactPoint", Required: false, MustSupport: false},
			},
		},
		"Encounter": {
			ResourceType: "Encounter",
			Profile:      profile,
			Fields: []FHIRFieldDefinition{
				{Path: "Encounter.class", Name: "Class", Type: "Coding", Required: true, MustSupport: true},
				{Path: "Encounter.period", Name: "Period", Type: "Period", Required: false, MustSupport: true},
			},
		},
	}, nil
}

func (c *SchemaFHIRTransformController) getMappingStatistics(rules []MappingRule) map[string]interface{} {
	stats := map[string]interface{}{
		"total": len(rules),
		"byConfidence": map[string]int{
			"high":   0,
			"medium": 0,
			"low":    0,
		},
		"byStatus": map[string]int{
			"mapped":   0,
			"unmapped": 0,
			"errors":   0,
		},
	}

	for _, rule := range rules {
		if conf, ok := stats["byConfidence"].(map[string]int); ok {
			conf[rule.Confidence]++
		}
		if rule.Enabled {
			if status, ok := stats["byStatus"].(map[string]int); ok {
				status["mapped"]++
			}
		}
	}

	return stats
}

func (c *SchemaFHIRTransformController) validateMappingCompleteness(rules []MappingRule, hl7Structure map[string]HL7FieldStructure, fhirStructure map[string]FHIRResourceStructure) []map[string]interface{} {
	var issues []map[string]interface{}

	// Check for unmapped required FHIR fields
	for resourceType, resource := range fhirStructure {
		for _, field := range resource.Fields {
			if field.Required || field.MustSupport {
				mapped := false
				for _, rule := range rules {
					if rule.FHIRResource == resourceType && rule.FHIRPath == field.Path && rule.Enabled {
						mapped = true
						break
					}
				}
				if !mapped {
					issues = append(issues, map[string]interface{}{
						"type":        "unmapped_required",
						"severity":    "error",
						"resource":    resourceType,
						"field":       field.Path,
						"description": fmt.Sprintf("%s.%s is required but not mapped", resourceType, field.Path),
					})
				}
			}
		}
	}

	return issues
}

func (c *SchemaFHIRTransformController) generateFieldMappingSuggestions(messageType, hl7Field, profile string) []map[string]interface{} {
	// Basic suggestion logic - enhance based on your existing services
	suggestions := []map[string]interface{}{}

	if strings.Contains(hl7Field, "PID.3") {
		suggestions = append(suggestions, map[string]interface{}{
			"fhirPath":      "Patient.identifier",
			"confidence":    "high",
			"transformType": "direct",
			"description":   "Patient identifier mapping",
			"rationale":     "PID.3 typically contains patient identifiers",
		})
	}

	return suggestions
}

func (c *SchemaFHIRTransformController) validateRulesAgainstSchemas(rules []MappingRule, messageType, profile string) map[string]interface{} {
	return map[string]interface{}{
		"valid":    true,
		"errors":   []string{},
		"warnings": []string{},
	}
}

func (c *SchemaFHIRTransformController) autoFixMappingIssues(rules []MappingRule, validationResults map[string]interface{}) []MappingRule {
	// Auto-fix logic can be implemented here
	return rules
}

func (c *SchemaFHIRTransformController) getDefaultMappingsForMessageType(messageType, profile string) []MappingRule {
	return []MappingRule{}
}
