// controllers/wizard_api_controller.go
// Fixed wizard API controller that matches your actual HL7 types

package controllers

import (
	"fmt"
	"net/http"
	"strconv"
	"strings"
	"time"

	"ezhealthkonnect/config"
	"ezhealthkonnect/fhir" // Added import for MappingRule
	"ezhealthkonnect/hl7"

	"github.com/gin-gonic/gin"
)

// WizardController handles wizard-related operations
type WizardController struct {
	config *config.Config
}

// NewWizardController creates a new wizard controller
func NewWizardController(cfg *config.Config) *WizardController {
	return &WizardController{
		config: cfg,
	}
}

// ================================
// Request/Response Types
// ================================

type WizardParseRequest struct {
	Content     string                 `json:"content" binding:"required"`
	MessageType string                 `json:"messageType"`
	Options     map[string]interface{} `json:"options"`
}

type WizardParseResponse struct {
	Data     *WizardParsedData `json:"data"`
	Metadata *WizardMetadata   `json:"metadata"`
	Error    string            `json:"error,omitempty"`
}

type WizardParsedData struct {
	Segments         map[string]interface{} `json:"segments"`
	ZSegments        map[string]interface{} `json:"zSegments"`
	EnhancedSegments map[string]interface{} `json:"enhancedSegments"`
	RawMessage       string                 `json:"rawMessage"`
}

type WizardMetadata struct {
	MessageType        string   `json:"messageType"`
	Version            string   `json:"version"`
	TotalSegments      int      `json:"totalSegments"`
	TotalFields        int      `json:"totalFields"`
	Timestamp          string   `json:"timestamp"`
	SendingApplication string   `json:"sendingApplication"`
	Warnings           []string `json:"warnings,omitempty"`
	Errors             []string `json:"errors,omitempty"`
}

// WizardMappingRuleView represents how the wizard UI sees a mapping rule
// This is for JSON responses, bridging the gap with the transformation engine
type WizardMappingRuleView struct {
	ID                   int                    `json:"id"`
	HL7Segment           string                 `json:"hl7_segment"`
	HL7Field             string                 `json:"hl7_field"`
	HL7Name              string                 `json:"hl7_name"`
	FHIRResource         string                 `json:"fhir_resource"`
	FHIRPath             string                 `json:"fhir_path"`
	TransformationType   string                 `json:"transformation_type"`
	TransformationConfig map[string]interface{} `json:"transformation_config"`
	Confidence           string                 `json:"confidence"`
	Enabled              bool                   `json:"enabled"`
	AutoGenerated        bool                   `json:"auto_generated"`
	Notes                string                 `json:"notes,omitempty"`
	Mapped               bool                   `json:"mapped"`
}

type MappingRulesResponse struct {
	Rules       []WizardMappingRuleView `json:"rules"`
	Metadata    interface{}             `json:"metadata"`
	LastUpdated string                  `json:"lastUpdated"`
}

type SaveRulesRequest struct {
	MessageType string                  `json:"messageType"`
	Rules       []WizardMappingRuleView `json:"rules"`
	Timestamp   string                  `json:"timestamp"`
}

type WizardInterfaceRequest struct {
	Name        string                 `json:"name" binding:"required"`
	Description string                 `json:"description"`
	Type        string                 `json:"type"`
	MessageType string                 `json:"messageType"`
	Source      map[string]interface{} `json:"source"`
	Target      map[string]interface{} `json:"target"`
	Mappings    map[string]interface{} `json:"mappings"`
	Deployment  map[string]interface{} `json:"deployment"`
	Metadata    map[string]interface{} `json:"metadata"`
}

// ================================
// Helper Methods for Mapping Rules
// ================================

// Helper method: Convert transformation engine MappingRule to wizard view
func (ctrl *WizardController) toWizardView(rule fhir.MappingRule) WizardMappingRuleView {
	// Extract transformation type from TransformLogic
	transformType := "direct" // default
	if rule.TransformLogic != nil {
		if typeVal, ok := rule.TransformLogic["type"].(string); ok {
			transformType = typeVal
		}
	}

	// Get human-readable name for HL7 field
	hl7Name := ctrl.getHL7FieldName(rule.HL7Segment, rule.HL7Field)

	// Convert TransformLogic to TransformationConfig for wizard
	transformConfig := make(map[string]interface{})
	if rule.TransformLogic != nil {
		transformConfig = rule.TransformLogic
	}

	return WizardMappingRuleView{
		ID:                   rule.ID,
		HL7Segment:           rule.HL7Segment,
		HL7Field:             rule.HL7Field,
		HL7Name:              hl7Name,
		FHIRResource:         rule.FHIRResource,
		FHIRPath:             rule.FHIRPath,
		TransformationType:   transformType,
		TransformationConfig: transformConfig,
		Confidence:           "high", // Default confidence
		Enabled:              true,   // Default enabled
		AutoGenerated:        true,   // Default auto-generated
		Mapped:               true,   // Default mapped
	}
}

// Helper method: Convert wizard view back to transformation engine MappingRule
func (ctrl *WizardController) fromWizardView(view WizardMappingRuleView) fhir.MappingRule {
	// Use TransformationConfig if available, otherwise create from TransformationType
	transformLogic := view.TransformationConfig
	if transformLogic == nil {
		transformLogic = map[string]interface{}{
			"type": view.TransformationType,
		}
	}

	return fhir.MappingRule{
		ID:             view.ID,
		HL7Segment:     view.HL7Segment,
		HL7Field:       view.HL7Field,
		FHIRResource:   view.FHIRResource,
		FHIRPath:       view.FHIRPath,
		TransformLogic: transformLogic,
		Priority:       view.ID, // Use ID as priority for now
		Required:       false,   // Default
	}
}

// Helper method: Get human-readable name for HL7 fields
func (ctrl *WizardController) getHL7FieldName(segment, field string) string {
	// Map common HL7 fields to readable names
	fieldMap := map[string]string{
		"MSH.3":  "Sending Application",
		"MSH.4":  "Sending Facility",
		"MSH.9":  "Message Type",
		"PID.3":  "Patient Identifier List",
		"PID.5":  "Patient Name",
		"PID.7":  "Date/Time of Birth",
		"PID.8":  "Administrative Sex",
		"PID.11": "Patient Address",
		"PID.13": "Phone Number - Home",
		"PV1.2":  "Patient Class",
		"PV1.3":  "Assigned Patient Location",
		"OBR.4":  "Universal Service Identifier",
		"OBX.3":  "Observation Identifier",
		"OBX.5":  "Observation Value",
		// Add more as needed
	}

	key := segment + "." + field
	if name, exists := fieldMap[key]; exists {
		return name
	}
	return segment + "." + field // Fallback to segment.field format
}

// ================================
// Register Routes with Gin
// ================================

func (ctrl *WizardController) RegisterRoutes(router *gin.RouterGroup) {
	// HL7 Parsing for wizard
	//router.POST("/hl7/parse", ctrl.ParseHL7)

	// Mapping Rules
	router.GET("/fhir/mapping/rules/:messageType", ctrl.GetMappingRules)
	router.PUT("/fhir/mapping/rules/:messageType", ctrl.SaveMappingRules)
	router.POST("/fhir/mapping/test", ctrl.TestTransformation)
	router.POST("/fhir/mapping/ai-suggest", ctrl.GenerateAISuggestions)

	// FHIR Validation
	router.POST("/fhir/validate/:resourceType", ctrl.ValidateFHIRResource)

	// Interface Management
	//router.POST("/interfaces", ctrl.CreateInterface)
}

// ================================
// Handler Methods
// ================================

// ParseHL7 handles HL7 message parsing for the wizard
func (ctrl *WizardController) ParseHL7(c *gin.Context) {
	var req WizardParseRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, WizardParseResponse{
			Error: fmt.Sprintf("Invalid request: %v", err),
		})
		return
	}

	if ctrl.config.VerboseLogging {
		fmt.Printf("🎯 Wizard HL7 Parse: %s (length: %d)\n", req.MessageType, len(req.Content))
	}

	// Use your existing HL7 parser
	result := hl7.ParseHL7Enhanced(req.Content)
	if result == nil {
		c.JSON(http.StatusInternalServerError, WizardParseResponse{
			Error: "Parser returned null result",
		})
		return
	}

	if !result.Success {
		c.JSON(http.StatusBadRequest, WizardParseResponse{
			Error: result.Error,
		})
		return
	}

	// Convert to wizard format - FIXED to match your HL7 types
	segments := make(map[string]interface{})
	zSegments := make(map[string]interface{})

	for segName, segment := range result.EnhancedSegments {
		segmentData := make(map[string]string)

		// FIXED: Simple iteration over Fields
		for i := 0; i < len(segment.Fields); i++ {
			fieldKey := strconv.Itoa(i + 1) // HL7 fields typically start at 1
			segmentData[fieldKey] = segment.Fields[i].Value
		}

		if strings.HasPrefix(segName, "Z") {
			zSegments[segName] = segmentData
		} else {
			segments[segName] = segmentData
		}
	}

	// Extract metadata - FIXED and simplified
	sendingApp := ""
	messageVersion := "2.5" // Default version

	// Try to extract sending application from MSH segment
	if mshSegment, exists := result.EnhancedSegments["MSH"]; exists && len(mshSegment.Fields) > 3 {
		sendingApp = mshSegment.Fields[3].Value
	}

	response := WizardParseResponse{
		Data: &WizardParsedData{
			Segments:         segments,
			ZSegments:        zSegments,
			EnhancedSegments: segments, // Same as segments for now
			RawMessage:       req.Content,
		},
		Metadata: &WizardMetadata{
			MessageType:        result.MessageType.Name,
			Version:            messageVersion, // FIXED: Use default since Version field doesn't exist
			TotalSegments:      len(result.EnhancedSegments),
			TotalFields:        ctrl.countTotalFields(result.EnhancedSegments), // FIXED: Pass correct type
			Timestamp:          time.Now().Format(time.RFC3339),
			SendingApplication: sendingApp,
			Warnings:           []string{},
			Errors:             []string{},
		},
	}

	c.JSON(http.StatusOK, response)
}

// GetMappingRules retrieves mapping rules for a message type
func (ctrl *WizardController) GetMappingRules(c *gin.Context) {
	messageType := c.Param("messageType")

	if ctrl.config.VerboseLogging {
		fmt.Printf("🔄 Loading mapping rules for: %s\n", messageType)
	}

	// TODO: Load from your database/storage
	// For now, return default rules based on message type
	rules := ctrl.getDefaultMappingRules(messageType)

	response := MappingRulesResponse{
		Rules: rules,
		Metadata: map[string]interface{}{
			"source":      "default",
			"messageType": messageType,
			"count":       len(rules),
		},
		LastUpdated: time.Now().Format(time.RFC3339),
	}

	c.JSON(http.StatusOK, response)
}

// SaveMappingRules saves mapping rules for a message type
func (ctrl *WizardController) SaveMappingRules(c *gin.Context) {
	messageType := c.Param("messageType")

	var req SaveRulesRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{
			"success": false,
			"error":   fmt.Sprintf("Invalid request: %v", err),
		})
		return
	}

	if ctrl.config.VerboseLogging {
		fmt.Printf("💾 Saving %d mapping rules for: %s\n", len(req.Rules), messageType)
	}

	// TODO: Save to your database/storage
	// Convert wizard rules to transformation engine format if needed
	engineRules := make([]fhir.MappingRule, len(req.Rules))
	for i, wizardRule := range req.Rules {
		engineRules[i] = ctrl.fromWizardView(wizardRule)
	}

	c.JSON(http.StatusOK, gin.H{
		"success": true,
		"saved":   len(req.Rules),
		"id":      fmt.Sprintf("mapping_%s_%d", messageType, time.Now().Unix()),
		"version": 1,
		"message": "Mapping rules saved successfully",
	})
}

// TestTransformation tests HL7 to FHIR transformation
func (ctrl *WizardController) TestTransformation(c *gin.Context) {
	var testData struct {
		HL7Message   string                  `json:"hl7_message"`
		MappingRules []WizardMappingRuleView `json:"mapping_rules"`
		Options      struct {
			ValidateFHIR    bool `json:"validate_fhir"`
			IncludeUnmapped bool `json:"include_unmapped"`
			DebugMode       bool `json:"debug_mode"`
		} `json:"options"`
	}

	if err := c.ShouldBindJSON(&testData); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{
			"success": false,
			"error":   fmt.Sprintf("Invalid request: %v", err),
		})
		return
	}

	if ctrl.config.VerboseLogging {
		fmt.Printf("🧪 Testing transformation with %d rules\n", len(testData.MappingRules))
	}

	// TODO: Use your existing FHIR transformation engine
	// Convert wizard rules to engine format
	engineRules := make([]fhir.MappingRule, len(testData.MappingRules))
	for i, wizardRule := range testData.MappingRules {
		engineRules[i] = ctrl.fromWizardView(wizardRule)
	}

	c.JSON(http.StatusOK, gin.H{
		"success": true,
		"fhir_resources": []gin.H{
			{
				"resourceType": "Patient",
				"id":           "example-patient",
				"name": []gin.H{
					{"family": "Doe", "given": []string{"John"}},
				},
			},
		},
		"validation_results": gin.H{
			"valid":    true,
			"errors":   []string{},
			"warnings": []string{},
		},
		"unmapped_fields":     []string{},
		"performance_metrics": gin.H{"duration": "0.5s"},
		"warnings":            []string{},
	})
}

// CreateInterface creates a new interface
func (ctrl *WizardController) CreateInterface(c *gin.Context) {
	var req WizardInterfaceRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{
			"success": false,
			"error":   fmt.Sprintf("Invalid request: %v", err),
		})
		return
	}

	if ctrl.config.VerboseLogging {
		fmt.Printf("🎯 Creating wizard interface: %s\n", req.Name)
	}

	// TODO: Save to your database using existing interface controller logic
	// You can call your existing CreateInterface method or similar

	interfaceID := fmt.Sprintf("wiz_%d", time.Now().Unix())

	c.JSON(http.StatusCreated, gin.H{
		"success": true,
		"interface": gin.H{
			"id":       interfaceID,
			"name":     req.Name,
			"status":   "active",
			"endpoint": fmt.Sprintf("/api/interfaces/%s", interfaceID),
			"created":  time.Now(),
		},
	})
}

// GenerateAISuggestions generates AI mapping suggestions
func (ctrl *WizardController) GenerateAISuggestions(c *gin.Context) {
	var request struct {
		HL7Data     interface{} `json:"hl7_data"`
		MessageType string      `json:"message_type"`
		Options     struct {
			ConfidenceThreshold    float64 `json:"confidence_threshold"`
			IncludeExplanations    bool    `json:"include_explanations"`
			SuggestTransformations bool    `json:"suggest_transformations"`
		} `json:"options"`
	}

	if err := c.ShouldBindJSON(&request); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{
			"success": false,
			"error":   fmt.Sprintf("Invalid request: %v", err),
		})
		return
	}

	if ctrl.config.VerboseLogging {
		fmt.Printf("🤖 Generating AI suggestions for: %s\n", request.MessageType)
	}

	// TODO: Implement AI suggestions based on your schema analysis

	c.JSON(http.StatusOK, gin.H{
		"success": true,
		"suggestions": []gin.H{
			{
				"field":      "PID.11",
				"suggestion": "Patient.address",
				"confidence": 0.9,
				"reason":     "Common mapping for patient address",
			},
			{
				"field":      "PID.13",
				"suggestion": "Patient.telecom",
				"confidence": 0.85,
				"reason":     "Phone number to telecom mapping",
			},
		},
		"confidence_scores":     gin.H{},
		"explanations":          gin.H{},
		"recommended_resources": []string{"Patient", "Encounter", "MessageHeader"},
	})
}

// ValidateFHIRResource validates FHIR resources
func (ctrl *WizardController) ValidateFHIRResource(c *gin.Context) {
	resourceType := c.Param("resourceType")

	var fhirResource map[string]interface{}
	if err := c.ShouldBindJSON(&fhirResource); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{
			"success": false,
			"error":   fmt.Sprintf("Invalid FHIR resource: %v", err),
		})
		return
	}

	if ctrl.config.VerboseLogging {
		fmt.Printf("✅ Validating FHIR %s resource\n", resourceType)
	}

	// TODO: Use your existing FHIR validation logic

	c.JSON(http.StatusOK, gin.H{
		"success":  true,
		"valid":    true,
		"errors":   []string{},
		"warnings": []string{},
		"score":    95,
	})
}

// ================================
// Helper Methods - FIXED
// ================================

// FIXED: Accept the correct type for EnhancedSegments
func (ctrl *WizardController) countTotalFields(segments map[string]hl7.EnhancedSegment) int {
	total := 0
	for _, segment := range segments {
		total += len(segment.Fields)
	}
	return total
}

// Updated to return WizardMappingRuleView instead of MappingRule
func (ctrl *WizardController) getDefaultMappingRules(messageType string) []WizardMappingRuleView {
	// Create rules using the transformation engine struct first
	engineRules := []fhir.MappingRule{
		{
			ID:           1,
			HL7Segment:   "MSH",
			HL7Field:     "3",
			FHIRResource: "MessageHeader",
			FHIRPath:     "source.name",
			TransformLogic: map[string]interface{}{
				"type": "direct",
			},
			Priority: 1,
			Required: false,
		},
		{
			ID:           2,
			HL7Segment:   "PID",
			HL7Field:     "3",
			FHIRResource: "Patient",
			FHIRPath:     "identifier",
			TransformLogic: map[string]interface{}{
				"type": "identifier",
			},
			Priority: 2,
			Required: false,
		},
		{
			ID:           3,
			HL7Segment:   "PID",
			HL7Field:     "5",
			FHIRResource: "Patient",
			FHIRPath:     "name",
			TransformLogic: map[string]interface{}{
				"type": "human_name",
			},
			Priority: 3,
			Required: false,
		},
		{
			ID:           4,
			HL7Segment:   "PID",
			HL7Field:     "7",
			FHIRResource: "Patient",
			FHIRPath:     "birthDate",
			TransformLogic: map[string]interface{}{
				"type": "date",
			},
			Priority: 4,
			Required: false,
		},
		{
			ID:           5,
			HL7Segment:   "PID",
			HL7Field:     "8",
			FHIRResource: "Patient",
			FHIRPath:     "gender",
			TransformLogic: map[string]interface{}{
				"type": "gender_code",
			},
			Priority: 5,
			Required: false,
		},
	}

	// Add message-type specific rules
	if strings.HasPrefix(messageType, "ADT") {
		engineRules = append(engineRules, fhir.MappingRule{
			ID:           6,
			HL7Segment:   "PV1",
			HL7Field:     "2",
			FHIRResource: "Encounter",
			FHIRPath:     "class",
			TransformLogic: map[string]interface{}{
				"type": "encounter_class",
			},
			Priority: 6,
			Required: false,
		})
	}

	// Convert to wizard view format
	wizardRules := make([]WizardMappingRuleView, len(engineRules))
	for i, rule := range engineRules {
		wizardRules[i] = ctrl.toWizardView(rule)
	}

	return wizardRules
}
