package services

import (
	"bytes"
	"context"
	"crypto/tls"
	"database/sql"
	"encoding/json"
	"fmt"
	"html/template"
	"io"
	"net"
	"net/http"
	"net/smtp"
	"os"
	"strings"
	"time"
)

// AlertNotificationService dispatches alert notifications to configured channels.
type AlertNotificationService struct {
	db         *sql.DB
	credStore  *CredentialStore // optional; used to decrypt system SMTP settings
	httpClient *http.Client
}

// NewAlertNotificationService creates a new dispatcher.
// An optional CredentialStore may be supplied to enable decryption of the
// system-wide SMTP settings stored in system_settings.
func NewAlertNotificationService(db *sql.DB, credStore ...*CredentialStore) *AlertNotificationService {
	svc := &AlertNotificationService{
		db:         db,
		httpClient: &http.Client{Timeout: 15 * time.Second},
	}
	if len(credStore) > 0 {
		svc.credStore = credStore[0]
	}
	return svc
}

// DispatchToChannel sends a notification to a single channel with 3-attempt retry.
func (n *AlertNotificationService) DispatchToChannel(ctx context.Context, ch *AlertChannel, alert *FiredAlert) error {
	var cfg map[string]interface{}
	if err := json.Unmarshal(ch.Config, &cfg); err != nil {
		return fmt.Errorf("invalid channel config: %w", err)
	}

	// Load system-wide SMTP settings once; used as a fallback inside sendEmail.
	systemSMTP := n.loadSystemSMTP(ctx)

	var lastErr error
	delays := []time.Duration{0, 2 * time.Second, 4 * time.Second}

	for attempt, delay := range delays {
		if delay > 0 {
			select {
			case <-ctx.Done():
				return ctx.Err()
			case <-time.After(delay):
			}
		}

		switch ch.ChannelType {
		case "email":
			lastErr = n.sendEmail(ctx, cfg, systemSMTP, alert)
		case "webhook":
			lastErr = n.sendWebhook(ctx, cfg, alert)
		case "slack":
			lastErr = n.sendSlack(ctx, cfg, alert)
		default:
			return fmt.Errorf("unknown channel type: %s", ch.ChannelType)
		}

		if lastErr == nil {
			return nil
		}
		_ = attempt
	}
	return fmt.Errorf("all dispatch attempts failed: %w", lastErr)
}

// loadSystemSMTP reads and decrypts the system-wide SMTP config from DB.
// Returns nil if unconfigured or DB is unavailable.
func (n *AlertNotificationService) loadSystemSMTP(ctx context.Context) map[string]interface{} {
	if n.db == nil {
		return nil
	}
	var raw string
	err := n.db.QueryRowContext(ctx, `SELECT value FROM system_settings WHERE key = 'smtp'`).Scan(&raw)
	if err != nil {
		return nil
	}
	data := []byte(raw)
	// Decrypt if a credential store is available
	if n.credStore != nil {
		if dec, err := n.credStore.DecryptConfig(json.RawMessage(raw)); err == nil {
			data = dec
		}
	}
	var cfg map[string]interface{}
	_ = json.Unmarshal(data, &cfg)
	// Only return if host is actually configured
	if host, _ := cfg["host"].(string); host == "" {
		return nil
	}
	return cfg
}

// ─── Email ─────────────────────────────────────────────────────────────────────

var emailHTMLTemplate = template.Must(template.New("alert_email").Parse(`<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>ezHealthKonnect Alert</title></head>
<body style="font-family:Arial,sans-serif;background:#f8fafc;margin:0;padding:20px">
  <div style="max-width:600px;margin:0 auto;background:#fff;border-radius:8px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,.12)">
    <div style="background:{{.SeverityColor}};padding:20px 24px">
      <h2 style="color:#fff;margin:0;font-size:18px">{{.SeverityLabel}} — {{.AlertType}}</h2>
      <p style="color:rgba(255,255,255,.85);margin:6px 0 0;font-size:13px">ezHealthKonnect Alert Management</p>
    </div>
    <div style="padding:24px">
      <p style="font-size:15px;color:#1e3a8a;margin:0 0 16px"><strong>{{.Message}}</strong></p>
      <table style="width:100%;border-collapse:collapse;font-size:13px">
        <tr><td style="padding:6px 0;color:#64748b;width:140px">Interface</td><td style="color:#1e293b">{{.InterfaceName}}</td></tr>
        <tr><td style="padding:6px 0;color:#64748b">Severity</td><td style="color:#1e293b">{{.Severity}}</td></tr>
        <tr><td style="padding:6px 0;color:#64748b">Alert Type</td><td style="color:#1e293b">{{.AlertType}}</td></tr>
        <tr><td style="padding:6px 0;color:#64748b">Fired At</td><td style="color:#1e293b">{{.CreatedAt}}</td></tr>
      </table>
      <div style="margin-top:24px">
        <a href="{{.AlertsURL}}" style="background:#db2777;color:#fff;padding:10px 20px;border-radius:6px;text-decoration:none;font-size:13px;font-weight:600">View in Dashboard</a>
      </div>
    </div>
    <div style="background:#f1f5f9;padding:12px 24px;font-size:11px;color:#94a3b8">
      This alert was generated by ezHealthKonnect. To manage alert rules visit the Alerts section.
    </div>
  </div>
</body>
</html>`))

type emailTemplateData struct {
	SeverityColor string
	SeverityLabel string
	AlertType     string
	InterfaceName string
	Severity      string
	Message       string
	CreatedAt     string
	AlertsURL     string
}

// sendEmail sends an alert notification email.
// Priority for each SMTP field: per-channel config → system SMTP settings (DB) → env var.
func (n *AlertNotificationService) sendEmail(_ context.Context, cfg map[string]interface{}, systemSMTP map[string]interface{}, alert *FiredAlert) error {
	// Helper to apply three-level fallback
	fallback := func(channelKey, systemKey, envKey string) string {
		if v := getStr(cfg, channelKey, ""); v != "" {
			return v
		}
		if systemSMTP != nil {
			if v := getStr(systemSMTP, systemKey, ""); v != "" {
				return v
			}
		}
		return os.Getenv(envKey)
	}

	smtpHost := fallback("smtp_host", "host", "SMTP_HOST")
	smtpPort := fallback("smtp_port", "port", "SMTP_PORT")
	smtpUser := fallback("smtp_user", "username", "SMTP_USER")
	smtpPass := fallback("smtp_password_enc", "password", "SMTP_PASSWORD")
	fromAddr := fallback("from", "from_address", "SMTP_FROM")
	appBaseURL := os.Getenv("APP_BASE_URL")
	if appBaseURL == "" {
		appBaseURL = "http://localhost:3000"
	}

	if smtpHost == "" {
		return fmt.Errorf("email channel: smtp_host not configured")
	}
	if smtpPort == "" {
		smtpPort = "587"
	}
	if fromAddr == "" {
		fromAddr = "alerts@ezhealthkonnect.local"
	}

	toRaw, _ := cfg["to"]
	var toAddrs []string
	switch v := toRaw.(type) {
	case []interface{}:
		for _, item := range v {
			if s, ok := item.(string); ok {
				toAddrs = append(toAddrs, s)
			}
		}
	case string:
		toAddrs = []string{v}
	}
	if len(toAddrs) == 0 {
		return fmt.Errorf("email channel: no recipients configured")
	}

	severityColor := "#f59e0b" // warning amber
	severityLabel := "WARNING"
	if alert.Severity == "critical" {
		severityColor = "#dc2626"
		severityLabel = "CRITICAL"
	} else if alert.Severity == "info" {
		severityColor = "#db2777"
		severityLabel = "INFO"
	}

	var htmlBuf bytes.Buffer
	_ = emailHTMLTemplate.Execute(&htmlBuf, emailTemplateData{
		SeverityColor: severityColor,
		SeverityLabel: severityLabel,
		AlertType:     alert.AlertType,
		InterfaceName: alert.InterfaceName,
		Severity:      strings.ToUpper(alert.Severity),
		Message:       alert.Message,
		CreatedAt:     alert.CreatedAt,
		AlertsURL:     appBaseURL + "/alerts.html",
	})

	subject := fmt.Sprintf("[%s] %s — %s", strings.ToUpper(alert.Severity), alert.AlertType, alert.InterfaceName)
	body := fmt.Sprintf(
		"To: %s\r\nFrom: %s\r\nSubject: %s\r\nMIME-Version: 1.0\r\nContent-Type: text/html; charset=UTF-8\r\n\r\n%s",
		strings.Join(toAddrs, ", "), fromAddr, subject, htmlBuf.String(),
	)

	addr := net.JoinHostPort(smtpHost, smtpPort)

	var auth smtp.Auth
	if smtpUser != "" {
		auth = smtp.PlainAuth("", smtpUser, smtpPass, smtpHost)
	}

	// STARTTLS
	tlsCfg := &tls.Config{ServerName: smtpHost, MinVersion: tls.VersionTLS12}
	conn, err := tls.Dial("tcp", addr, tlsCfg)
	if err != nil {
		// Fall back to plain SMTP with STARTTLS upgrade
		return smtp.SendMail(addr, auth, fromAddr, toAddrs, []byte(body))
	}
	defer conn.Close()

	client, err := smtp.NewClient(conn, smtpHost)
	if err != nil {
		return err
	}
	defer client.Quit()

	if auth != nil {
		if err := client.Auth(auth); err != nil {
			return err
		}
	}
	if err := client.Mail(fromAddr); err != nil {
		return err
	}
	for _, rcpt := range toAddrs {
		if err := client.Rcpt(rcpt); err != nil {
			return err
		}
	}
	wc, err := client.Data()
	if err != nil {
		return err
	}
	if _, err := io.WriteString(wc, body); err != nil {
		return err
	}
	return wc.Close()
}

// ─── Generic Webhook ───────────────────────────────────────────────────────────

// webhookPayload is the standard JSON body sent to all webhook/Slack channels.
type webhookPayload struct {
	Source        string                 `json:"source"`
	AlertType     string                 `json:"alert_type"`
	Severity      string                 `json:"severity"`
	Message       string                 `json:"message"`
	InterfaceID   *string                `json:"interface_id"`
	InterfaceName string                 `json:"interface_name"`
	FiredAt       string                 `json:"fired_at"`
	Context       map[string]interface{} `json:"context,omitempty"`
}

func buildWebhookPayload(alert *FiredAlert) webhookPayload {
	return webhookPayload{
		Source:        "ezHealthKonnect",
		AlertType:     alert.AlertType,
		Severity:      alert.Severity,
		Message:       alert.Message,
		InterfaceID:   alert.InterfaceID,
		InterfaceName: alert.InterfaceName,
		FiredAt:       alert.CreatedAt,
	}
}

func (n *AlertNotificationService) sendWebhook(ctx context.Context, cfg map[string]interface{}, alert *FiredAlert) error {
	url := getStr(cfg, "url", "")
	if url == "" {
		return fmt.Errorf("webhook channel: url not configured")
	}
	method := strings.ToUpper(getStr(cfg, "method", "POST"))
	timeoutSecs := int(getFloat(cfg, "timeout_seconds", 10))

	payload, _ := json.Marshal(buildWebhookPayload(alert))

	req, err := http.NewRequestWithContext(ctx, method, url, bytes.NewReader(payload))
	if err != nil {
		return err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("User-Agent", "ezHealthKonnect-AlertManager/1.0")

	// Custom headers (e.g. Authorization)
	if headers, ok := cfg["headers"].(map[string]interface{}); ok {
		for k, v := range headers {
			if sv, ok := v.(string); ok {
				req.Header.Set(k, sv)
			}
		}
	}

	client := &http.Client{Timeout: time.Duration(timeoutSecs) * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return fmt.Errorf("webhook returned HTTP %d", resp.StatusCode)
	}
	return nil
}

// ─── Slack ─────────────────────────────────────────────────────────────────────

func (n *AlertNotificationService) sendSlack(ctx context.Context, cfg map[string]interface{}, alert *FiredAlert) error {
	webhookURL := getStr(cfg, "webhook_url", "")
	if webhookURL == "" {
		return fmt.Errorf("slack channel: webhook_url not configured")
	}
	channel := getStr(cfg, "channel", "#alerts")
	username := getStr(cfg, "username", "ezHealthKonnect")
	iconEmoji := getStr(cfg, "icon_emoji", ":hospital:")

	color := "#f59e0b"
	if alert.Severity == "critical" {
		color = "#dc2626"
	} else if alert.Severity == "info" {
		color = "#db2777"
	}

	title := fmt.Sprintf("[%s] %s", strings.ToUpper(alert.Severity), alert.AlertType)

	slackBody := map[string]interface{}{
		"channel":    channel,
		"username":   username,
		"icon_emoji": iconEmoji,
		"text":       title,
		"attachments": []map[string]interface{}{
			{
				"color": color,
				"fields": []map[string]interface{}{
					{"title": "Message", "value": alert.Message, "short": false},
					{"title": "Interface", "value": alert.InterfaceName, "short": true},
					{"title": "Severity", "value": strings.ToUpper(alert.Severity), "short": true},
					{"title": "Fired At", "value": alert.CreatedAt, "short": true},
				},
				"footer": "ezHealthKonnect Alert Management",
			},
		},
	}

	body, _ := json.Marshal(slackBody)
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, webhookURL, bytes.NewReader(body))
	if err != nil {
		return err
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := n.httpClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode >= 400 {
		return fmt.Errorf("slack webhook returned HTTP %d", resp.StatusCode)
	}
	return nil
}

// ─── Helpers ───────────────────────────────────────────────────────────────────

func getStr(m map[string]interface{}, key, fallback string) string {
	if v, ok := m[key]; ok {
		if s, ok := v.(string); ok && s != "" {
			return s
		}
	}
	return fallback
}

func getFloat(m map[string]interface{}, key string, fallback float64) float64 {
	if v, ok := m[key]; ok {
		switch n := v.(type) {
		case float64:
			return n
		case int:
			return float64(n)
		}
	}
	return fallback
}
