-- V274: "Connect a Device" guided templates -- new `device` category.
-- Organized by CONNECTION TYPE (protocol + transport), not by device brand
-- or model -- a device picks whichever type template matches what its own
-- setup screen offers, with no new template needed per vendor/model. Pure
-- data on the existing interface_templates table (V67/V92) -- no schema
-- change.
--
-- One real, working template today: "HL7 over TCP/IP". It reuses the
-- already-built, already-tested tcp_mllp_inbound host-query/ack mechanism
-- (services/connectors/tcp_mllp_inbound.go) and the exact DSR^Q03-answering
-- mechanism proven working against a real mock analyzer this session
-- (QRD.8 sample-ID parsing via the real enhancedSegments.QRD.Fields[].Key/
-- .Value shape ParseToJSON produces).
--
-- "ASTM over Serial Port" and "ASTM over TCP/IP" are deliberately NOT
-- created as templates here -- no serial connector and no ASTM engine
-- exist anywhere in this codebase today (confirmed via direct grep), so a
-- clickable template for either would not actually work end to end. Named
-- as a future gap in this template's own guide text instead of shipped as
-- a non-functional placeholder.
--
-- Honest limitation, not silently hidden: the "Derive Order Lookup" step
-- below is a PLACEHOLDER -- it always reports "no pending order found" so a
-- real instrument gets a valid, well-formed DSR^Q03 reply instead of
-- hanging, but it does not call a real HIS. A real bidirectional
-- deployment needs this step replaced with (or followed by) a real lookup
-- against the customer's own HIS order API -- that contract can't be known
-- ahead of time (same "HIS side deliberately left open" decision as the
-- rest of this device-integration plan). The wizard still collects the HIS
-- lookup URL as an optional field so the integrator has somewhere to plug
-- it in.
--
-- Port number (6612) is deliberately inside the real, Docker-mapped
-- TCP/MLLP range (docker-compose.yml: "6610-6670:6610-6670") -- editable by
-- the user at wizard time, but must default to something actually reachable
-- in this deployment, not an arbitrary unmapped port.
--
-- This file is generated by scratchpad/gen_v274.js (not hand-escaped) to
-- avoid the real, easy-to-get-wrong triple-escaping risk of JS script
-- content -> JSON string -> SQL string literal.

INSERT INTO interface_templates
    (id, name, slug, description, category, subcategory, tags, icon, difficulty,
     source_connector_type, source_config_template,
     target_connector_type, target_config_template,
     pipeline_config, message_type,
     required_connection_fields, sanitized_fields, preview_steps,
     estimated_setup_minutes, is_system, is_public, author, usage_count)
VALUES

-- HL7 over TCP/IP — any network-connected HL7 v2 lab instrument
(
    gen_random_uuid(),
    'HL7 over TCP/IP',
    'device-hl7-tcp',
    'Connect any lab instrument that speaks HL7 v2 over a network (TCP/IP) connection — many Mindray, Roche, Abbott, and other analyzers support this mode. Receives lab results and, optionally, answers the instrument''s own live order-lookup query before it processes a sample. Pick this template if your instrument''s own setup screen offers an "HL7" protocol choice over a network/Ethernet connection (not RS232/serial, and not "ASTM").',
    'device',
    'network',
    ARRAY['hl7v2','tcp-mllp','network','tcp-ip','bidirectional','lab-instrument'],
    '🔌',
    'beginner',
    'tcp_mllp_inbound',
    '{"host":"0.0.0.0","port":6612,"ack":{"mode":"immediate","on_error":"suppress"},"host_query":{"enabled":false,"message_types":["QRY"],"pipeline_message_type":"QRY"}}',
    'http_outbound',
    '{"method":"POST","content_type":"application/fhir+json","auth_type":"bearer","timeout_seconds":30}',
    '{"execution_groups":[{"sequence":5,"steps":[{"step_name":"TCP/MLLP Inbound (HL7 v2)","step_type":"connector.inbound","sequence":5,"config":{"connectorType":"tcp_mllp_inbound","config":{"host":"0.0.0.0","port":6612,"max_connections":5,"ack":{"mode":"immediate","on_error":"suppress","sending_app":"ezHealthKonnect","sending_facility":"EHK","text_success":"Message received successfully","text_error":"Message processing error"},"host_query":{"enabled":false,"message_types":["QRY"],"pipeline_message_type":"QRY","timeout_seconds":10,"on_failure_nack":true}},"timeoutMs":30000},"enabled":true,"required":true}]},{"sequence":10,"steps":[{"step_name":"Validate HL7 ORU","step_type":"enrichment.validation","sequence":10,"config":{"format":"hl7v2","required_segments":["MSH","PID","OBR","OBX"],"fail_on_error":false},"enabled":true,"required":false}]},{"sequence":20,"steps":[{"step_name":"HL7 → FHIR Transform (ORU^R01)","step_type":"hl7_fhir_transform","sequence":20,"config":{"message_type":"ORU^R01","target_resources":["Observation","DiagnosticReport","Patient"],"include_metadata":true},"enabled":true,"required":true}]},{"sequence":30,"steps":[{"step_name":"Validate FHIR Bundle","step_type":"enrichment.validation","sequence":30,"config":{"format":"fhir_r4","fail_on_error":false},"enabled":true,"required":false}]},{"sequence":200,"steps":[{"step_name":"Derive Order Lookup","step_alias":"derive_order_lookup","step_type":"enrichment.script","sequence":200,"config":{"script":"// PLACEHOLDER: replace with a real lookup against your HIS before relying\n// on bidirectional/host-query mode in production. This stub always reports\n// \"no pending order found\" so the instrument still gets a valid, well-formed\n// reply instead of hanging or erroring -- it never fabricates real order\n// data. Only runs its real logic when host_query.enabled is on and the\n// inbound message is the instrument''s own QRY^Q02 order query (harmless\n// no-op otherwise since nothing downstream of a normal ORU result reads\n// its output).\nvar msg = input.message || input;\nvar qrd = (msg.enhancedSegments && msg.enhancedSegments.QRD) || {};\nvar fields = qrd.Fields || [];\nvar sampleField = fields.filter(function(f) { return f.Key === ''QRD.8''; })[0];\nvar sampleId = sampleField ? sampleField.Value : '''';\n\n({ sample_id: sampleId, test_code: ''UNKNOWN'', test_name: ''No pending order found -- connect this step to your HIS to enable real order lookup'' });"},"enabled":true,"required":false}]},{"sequence":210,"steps":[{"step_name":"Build DSR Reply","step_alias":"build_dsr_reply","step_type":"hl7.build","sequence":210,"config":{"messageType":"DSR","triggerEvent":"Q03","version":"2.5.1","segments":[{"segment":"QAK","cardinality":"single","fields":[{"fieldKey":"QAK.1","literalValue":"Q001"},{"fieldKey":"QAK.2","literalValue":"AA"}]},{"segment":"DSP","cardinality":"single","fields":[{"fieldKey":"DSP.1","literalValue":"1"},{"fieldKey":"DSP.2","sourcePath":"steps.derive_order_lookup.step_output.sample_id"},{"fieldKey":"DSP.3","sourcePath":"steps.derive_order_lookup.step_output.test_code"},{"fieldKey":"DSP.4","sourcePath":"steps.derive_order_lookup.step_output.test_name"}]}]},"enabled":true,"required":false}]},{"sequence":295,"steps":[{"step_name":"Deliver Results to HIS","step_type":"connector.outbound","sequence":295,"config":{"connectorType":"http_outbound","config":{"method":"POST","content_type":"application/fhir+json","auth_type":"bearer","timeout_seconds":30},"contentField":"fhirBundle","contentType":"application/fhir+json"},"enabled":true,"required":true}]}]}',
    'ORU^R01',
    '[{"section":"source","field":"port","label":"Port Number","type":"number","hint":"The network port this server listens on. Enter this same number into the instrument''s own LIS/host communication settings.","required":true},{"section":"source","field":"host_query.enabled","label":"Does this instrument ask for the order before running a test?","type":"boolean","hint":"Turn on for bidirectional mode (the instrument queries for pending orders before processing a sample). Leave off for one-way result reporting only.","required":false},{"section":"target","field":"endpoint","label":"Results Delivery API URL","type":"url","hint":"Where completed lab results are sent, e.g. https://your-his.example.org/api/results","required":true},{"section":"target","field":"bearer_token","label":"Bearer Token","type":"password","hint":"Authorization token for your HIS API, if required","required":false},{"section":"target","field":"his_order_lookup_url","label":"Order-Lookup API URL","type":"url","hint":"Only needed if the toggle above is on. Ask your HIS vendor for the endpoint that returns pending orders for a given sample ID.","required":false}]',
    ARRAY['source.port','target.endpoint','target.bearer_token'],
    '[{"name":"Receive over TCP/IP","icon":"🔌","step_type":"connector.inbound"},{"name":"HL7→FHIR Transform","icon":"🔄","step_type":"hl7_fhir_transform"},{"name":"Answer Order Query","icon":"🔍","step_type":"hl7.build"},{"name":"Deliver to HIS","icon":"📤","step_type":"connector.outbound"}]',
    10,
    true,
    true,
    'ezHealthKonnect',
    0
);

-- ─────────────────────────────────────────────────────────────────────────────
-- User guide
-- ─────────────────────────────────────────────────────────────────────────────
UPDATE interface_templates
SET user_guide = $GUIDE$
# HL7 over TCP/IP

## Who this is for

Any lab instrument whose own setup screen lets you choose **HL7** as the
protocol and **TCP/IP / Network / Ethernet** as the connection type — not
serial/RS232, and not "ASTM". This covers many Mindray, Roche, Abbott, and
similar chemistry/hematology analyzers. If your instrument's manual instead
says "ASTM" or "RS232/Serial Port", this template is not the right fit —
see the note at the bottom.

## What you need before you start

- A network cable from the instrument to the same network this server is reachable on
- Access to the instrument's own LIS/host communication settings screen
- Your hospital's HIS results-delivery endpoint (ask your HIS vendor/admin if you don't already have it)

## Setup steps

1. **Pick a port number.** The default above is already chosen to work with this deployment -- you can keep it unless you have a reason to change it.
2. **On the instrument itself**, open its LIS/host communication setup screen, choose the **HL7** protocol (not ASTM), and enter this server's network address plus the **same port number** you entered above.
3. **"Does this instrument ask for the order before running a test?"** -- most analyzers that support this can work either way:
   - **Off (default)**: the instrument just sends results after running a test. Simplest setup.
   - **On**: the instrument will pause and ask this system for pending orders before running each sample -- only turn this on if the instrument's own settings screen is configured for "bidirectional" or "host query" mode.
4. **Enter your Results Delivery API URL.** This is where completed test results get sent.
5. If you turned the order-lookup toggle on, also enter your **Order-Lookup API URL** if you have one. If you don't have this yet, you can leave it blank for now -- the instrument will still get a valid reply, it just won't contain a real order (see note below).

## A note on bidirectional/host-query mode

When the toggle above is on, this system will answer the instrument's own live question ("what's ordered for this sample?") in real time, while the sample is sitting on the instrument waiting for an answer. Out of the box, this template's answer-building step is a **placeholder** -- it always replies "no pending order found" so the instrument gets a valid response instead of hanging, but it does not yet look up a real order from your HIS. An integration engineer needs to connect that step to your actual HIS's order-lookup API before this mode is fully useful in production -- ask ezHealthKonnect support or your integrator if you need help with that step.

## Advanced tuning

Acknowledgment timing/wording and detailed host-query settings (message types, timeout, failure behavior) can be fine-tuned later in **Pipeline Builder**, under this interface's connector step's **Acknowledgment** and **Host Query** tabs -- the defaults here cover the common case.

## If your instrument uses ASTM or a Serial (RS232) connection instead

Those are **not supported yet**. ASTM and raw serial-port connectivity are
a different protocol/transport combination that this platform doesn't have
a working connector for today -- using this template with that kind of
instrument will not work. This is a named, planned gap, not a hidden one;
ask your integrator about timing if you need it.
$GUIDE$
WHERE slug = 'device-hl7-tcp';
